### ISSUE TITLE
dataset

### ISSUE THREAD

**Issue by jiejie1993** [gmlyytt-YANG/face-alignment-occlusion-detection#1]
what kind of the dataset you use? could you give me the dataset ? my qq mail is 384300189@qq,com,thank you

**Comment by gmlyytt-YANG** [comment]
I downloaded the dataset in [IBUG](https://ibug.doc.ic.ac.uk/). You can find LFW68, HELEN68, IBUG68 and AFW68 there. And indices of images in these datasets can be found [here](https://github.com/zhusz/CVPR15-CFSS/tree/master/data).  Wish you have a good time.
